### ISSUE TITLE
Erratic behavior 

### ISSUE THREAD

**Issue by mgm350** [huyng/incertae#1]
Hello!  I am using your code to create a neural network.  When it works it works wonderfully, but about 50% of the time it goes nuts and gives me outrageous values.  Has this happened to you?  It appears as if every other time I run it, the index of si and mu changes and so the results become erratic. 

Also I would like to thank you for developing this code!

**Comment by mgm350** [comment]
I found the issue. It was with my code not yours.  Thanks!

**Comment by huyng** [comment]
cool glad you found the issue, what was it btw?

**Comment by mgm350** [comment]
I had early stopping implimented and it was too sensitive. Silly mistake in hindsight but its fixed now!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
